name: aurum-jenkins

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: aurum_jenkins
    user: root
    ports:
      - "8090:8080"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD:-admin123}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/univates/aurum-fintech:/home/univates/aurum-fintech
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - ./jenkins/jobs/deploy-aurum:/var/jenkins_home/jobs/deploy-aurum

volumes:
  jenkins_home:
