sonar.projectKey=aurum-fintech
sonar.projectName=Aurum Fintech
sonar.organization=jeferson-scheibler
sonar.sources=app.py
sonar.tests=test_app.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
